#!/bin/sh
#
#~ url=http://localhost:6570/netscan.cgi
url=http://nd3.localnet:6570/netscan.cgi

urlencode() { #$ encode string according to URL escape rules
  #$ :usage: urlencode "string"
  #$ :param string: string to encode
  #$ :output: encoded string
  #$
  #$ Encode a "string" following URL encoding rules
  local l=${#1} i=0
  while [ $i -lt $l ]
  do
    local c=${1:$i:1}
    case "$c" in
      [a-zA-Z0-9.~_-]) printf "$c" ;;
      ' ') printf + ;;
      *) printf '%%%.2X' "'$c"
    esac
    i=$(expr $i + 1)
  done
}

#
# Makes us of npqs mode...
#
qstr='?stderr=hdr&npqs'
for i in "$@"
do
  qstr="$qstr&$(urlencode "$i")"
done

wget -nv -S -O- "$url$qstr"
